{"name": "test_get_user_orders_unauthorized", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('client', <FixtureRequest for <Function test_get_user_orders_unauthorized>>)", "trace": "file C:\\Python\\qa_python_projects\\Diplom\\Diplom_2\\tests\\test_order_retrieval.py, line 7\n  def test_get_user_orders_unauthorized(client):\nE       fixture 'client' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Python\\qa_python_projects\\Diplom\\Diplom_2\\tests\\test_order_retrieval.py:7"}, "start": 1729961600483, "stop": 1729961600483, "uuid": "a7e71bb6-84b7-4777-8051-b3e52a31a965", "historyId": "91446a14f42683a52064bcd6299af5ed", "testCaseId": "91446a14f42683a52064bcd6299af5ed", "fullName": "tests.test_order_retrieval#test_get_user_orders_unauthorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_retrieval"}, {"name": "host", "value": "WorkPC"}, {"name": "thread", "value": "16360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_retrieval"}]}