{"name": "test_create_existing_user", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 409\n +  where 403 = <Response [403]>.status_code", "trace": "client = <utils.api_client.ApiClient object at 0x0000019F4D84FB00>\n\n    def test_create_existing_user(client):\n        data = {\"email\": \"unique@example.com\", \"password\": \"password\", \"name\": \"UniqueUser\"}\n        client.create_user(data)\n        response = client.create_user(data)\n>       assert response.status_code == 409\nE       assert 403 == 409\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_user_creation.py:18: AssertionError"}, "start": 1729961600734, "stop": 1729961600829, "uuid": "a574c7d0-f7b6-4cab-b37d-baef2c4f7f93", "historyId": "8a75cc68d587eeadf504dde162e293f2", "testCaseId": "8a75cc68d587eeadf504dde162e293f2", "fullName": "tests.test_user_creation#test_create_existing_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creation"}, {"name": "host", "value": "WorkPC"}, {"name": "thread", "value": "16360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creation"}]}